# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# warning: 不要在配置文件中使用 tab 制表符.

# Site settings
title: Jue's Blog
email: kousuke@163.com
description: > # this means to ignore newlines until "baseurl:"
  博客内容主要是小觉的生活琐事、在工作中或学习中整理出来的知识。
  当然，有时候也会推荐一些有趣的站点、实用的工具等。
baseurl: ""
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:  kousuke2010

# Paginator
gems: [jekyll-paginate]
paginate: 3 # 每页显示
paginate_path: "page:num"

# 排除 build 文件
# exclude:
#   - "/node_modules/"
#   - "package.json"
#   - "gulpfile.js"

# Build settings
markdown: kramdown
